# Generated by Django 4.0.3 on 2022-03-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fragrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scent', models.CharField(max_length=300)),
                ('seasonal_collection', models.CharField(max_length=300)),
                ('color', models.CharField(max_length=200)),
                ('gift_quantity', models.IntegerField()),
                ('wick_count', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
